### ISSUE TITLE
LCD keypad doesnt work?

### ISSUE THREAD

**Issue by bales0** [SHARPENTIERS/MZ-SD2CMT#3]
Hi,
I would like to renew my SHARP MZ-800 with MZ-SD2CMT as I have no cassete player now. Found this great project. Successfuly compile and run on Mega. LCD is showing first file, but it looks like LCD keypad doesnt work. No reaction from key push.
Im not able to check the code as Im not experienced, but from first view it looks like there is no routine to read A0 voltage from LCD keypad to decode keypress.
Could you please help?
Thank you.

**Comment by hlide** [comment]
Hi, glad to see my project inspires you. So, it was for an MZ-800. Can you give more details about what LCD keypad you use? A link to where you bought may be helpful.

**Comment by hlide** [comment]
I checked that the keypad is enabled by default in the source:
https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.input.h#L3

If you power the Mega through an USB cable plugged to your PC, you can use the serial terminal to get the value whenever you press a button on the keypad. Take note of the value for each button and give them to me. Preferably done without the MZ-800 connected to Mega as it is not a right thing to let USB power the MZ-800 or to let MZ-800 powering the PC USB.

**Comment by hlide** [comment]
Also, you can join me at https://discord.com/channels/1197483745389854760/1208344566521004073.

**Comment by hlide** [comment]
Mine was an old version V1 which may have a different order of voltages per key than yours and the source only works for V1. That's the reason I need more details about yours so I can add a new version working with yours.

https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L26-L38

**Comment by bales0** [comment]
Hi, than you for reply.
Im using this shield (probably China clone): D1 Robot
![IMG_20240721_194820](https://github.com/user-attachments/assets/c81b133b-1f57-46c6-986c-a0917f4d7865)

When I checked RS232 it cycle in strange error:
![IMG_20240721_195217](https://github.com/user-attachments/assets/2d7c5158-083a-411d-b0ed-f5d4723dff18)

I have compiled it in Arduino 1.8.5 due to new compiler incompatibility:
<img width="1280" alt="compiled" src="https://github.com/user-attachments/assets/a3490689-b250-4558-b505-b75be04b4bd8">

I cant see ADC values, but measured voltage:
Right: 0V
Up: 0.650V
Down: 1.508V
Left: 2.354V
Select: 3.533V

As I understand LCD keypad shield examples, there should be voltage range for each keypress (didnt found it in your code)

BR,
Aleš

**Comment by hlide** [comment]
To get the value, you simply need to use the serial monitor of Arduino IDE.

The order of buttons is the same as V1. Now, I'm not sure how to compute the voltage into BVx value because there is no warranty 1023 will be 5V (or 3.3V as I'm not sure). A long time ago I'm no longer programming in Arduino AVR... 

Each pressed button has its voltage. If you press two buttons, you'll get a voltage in-between. My code was done as such as it will only accept one pressed button just for your information, so it will accept them in range [BVx-5, BVx+5] (BV0, BV1, BV2, BV3 and BV4]

What I need is to see what the Mega is reading in its ADC A0 and my code will display it on USB serial. I don't understand the first image. And I cannot open both image to have them bigger as they seem to be private. 


"As I understand LCD keypad shield examples, there should be voltage range for each keypress (didnt found it in your code)"
They are there in ADC 0-1023 values as expected from Mega :
https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L24-L38

You can try to increase "delta" value as it is used to check a button is pressed if its ADC value is in the range [BVx-delta, BVx+delta]. But honestly, you can have those BVx values through the USB serial output whenever you press a button.

**Comment by bales0** [comment]
Hi, I used terminal to see COM but I can see just this message:
"
The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.
The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.
The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.
The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.
The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.
The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.
The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.
"

**Comment by bales0** [comment]
Hi, based on your hints, I have edited the code (replace decode(results) with decode(), so serial showed keypad ADC (I have changed acordingly ADC values as bellow). Now it shows:
"
Input device: rotary encoder.
Input device: TTP223 KeyPad.
MZ-SD2CMT
     41601 2000-10-11 10:46 Jason.mzf
TTP223: ----||0
0
83
133
1DF
2D0
"
But no reaction of LCD. Is is dependent on MOTOR and SENSE values and need to be connected to real MZ CMT port?
Selecting next mzf file doesnt work, so thats why I thought that keypad doesnt work.

BR,
Ales

**Comment by bales0** [comment]
Hi, still the keypads dont work. It reads the value from keypad, but doesnt react even I have cjanged the values to the same as from serial monitor.

**Comment by hlide** [comment]
Sorry, I was so busy with my work that I didn't watch my emails. So in the end, you got values when pressing keys (I see some hexa values). Did you change the values BV0-BV4 according to what you read? Because if you didn't change them, it is normal that there is no feedback to LCD since the difference is bigger than the delta value.

The values should be :
 static constexpr int BV0 = 0x0000; // TODO: make it configurable at run-time? 
 static constexpr int BV1 = 0x0083; // TODO: make it configurable at run-time? 
 static constexpr int BV2 = 0x0133; // TODO: make it configurable at run-time? 
 static constexpr int BV3 = 0x01DF; // TODO: make it configurable at run-time? 
 static constexpr int BV4 = 0x02D0; // TODO: make it configurable at run-time?

**Comment by hlide** [comment]
Regarding the LCD, I'm checking the datasheet of your LCD and they have the same pins. Oh, your picture is showing LCD is working. Note that if you select an entry, you can have info on serial port : https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.display.serial.h#L9

Let me check what happens...

**Comment by hlide** [comment]
In the loop, we get the input code to act accordingly:

https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.ino#L952-L974

You could add serial usb printing to see if a input code is received.

https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.ino#L137-L168

As you can see, there is a call to Display.displayCode(...) so I'm a little surprise you won't get here.

I suppose that you don't have specific issue to access SD (though Storage instance).

As for MOTOR and SENSE,  there are used when you call playWAV(); or playMZF();

**Comment by hlide** [comment]
And yes, you must connect SENSE and MOTOR! I design it as a replacement of the internal tape player, not as an external tape player and yes, MOTOR and SENSE are mandatory. Also, beware the schematic I used has the pin number in a "random" order so you should connect the tape wire according the pin number, not the pin position.

I redraw that part of schematic to have the pin numbers in the right position order:
![image](https://github.com/user-attachments/assets/bf449eed-13eb-49c0-9975-d105c5759346)

Also, regarding EX READ and EX WRITE (the two external jacks for an external tape player/recorder) are not used for many reasons:
- using external cassette recorders does not allow the cassette to be reliably saved for playback from another cassette player.
- using external cassette players requires you to calibrate the volume, making this a tedious task with cassettes recorded by different recorders, including the internal one.
- you need a dongle that connects the EX READ, EX WRITE and GND signals to the READ, WRITE and SENSE signals respectively.
- Ultra-fast mode (loading at the speed the Z80 can handle) requires the MOTOR and SENSE signals.
For all these reasons, this project can only replace an internal drive, not an external one.

**Comment by bales0** [comment]
> Sorry, I was so busy with my work that I didn't watch my emails. So in the end, you got values when pressing keys (I see some hexa values). Did you change the values BV0-BV4 according to what you read? Because if you didn't change them, it is normal that there is no feedback to LCD since the difference is bigger than the delta value.
> 
> The values should be : static constexpr int BV0 = 0x0000; // TODO: make it configurable at run-time? static constexpr int BV1 = 0x0083; // TODO: make it configurable at run-time? static constexpr int BV2 = 0x0133; // TODO: make it configurable at run-time? static constexpr int BV3 = 0x01DF; // TODO: make it configurable at run-time? static constexpr int BV4 = 0x02D0; // TODO: make it configurable at run-time?

Hi,
yes I have changed the values according the information from terminal.
Also I have tried to change delta in case the ADC is not stable.
But it didnt help.

**Comment by bales0** [comment]
> And yes, you must connect SENSE and MOTOR! I design it as a replacement of the internal tape player, not as an external tape player and yes, MOTOR and SENSE are mandatory. Also, beware the schematic I used has the pin number in a "random" order so you should connect the tape wire according the pin number, not the pin position.
> 
> I redraw that part of schematic to have the pin numbers in the right position order: ![image](https://private-user-images.githubusercontent.com/56785/352672872-bf449eed-13eb-49c0-9975-d105c5759346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NTA4NzUsIm5iZiI6MTcyMjc1MDU3NSwicGF0aCI6Ii81Njc4NS8zNTI2NzI4NzItYmY0NDllZWQtMTNlYi00OWMwLTk5NzUtZDEwNWM1NzU5MzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA1NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMmFjMDhmMWI5M2NkNjAxY2M1N2VlMzY4NmE2N2M4MzE2NzRjZjhjMjk5Yjk5ZjVjMzkyZGJjMTQ0OGVmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.REcNFCaVF5oWX4ZdcjBxUlTNWLKA12InLIQqt4qntE8)
> 
> Also, regarding EX READ and EX WRITE (the two external jacks for an external tape player/recorder) are not used for many reasons:
> 
> * using external cassette recorders does not allow the cassette to be reliably saved for playback from another cassette player.
> * using external cassette players requires you to calibrate the volume, making this a tedious task with cassettes recorded by different recorders, including the internal one.
> * you need a dongle that connects the EX READ, EX WRITE and GND signals to the READ, WRITE and SENSE signals respectively.
> * Ultra-fast mode (loading at the speed the Z80 can handle) requires the MOTOR and SENSE signals.
>   For all these reasons, this project can only replace an internal drive, not an external one.

Yes, I understand that this project uses the max speed of communication for FAST load. Thats why I like it and plan to 3D print cover and implement directly to MZ (I have MZ-800 without internal CMT).
Just to be sure, communication timing of your SD2CMT is for MZ-700? Will it work with MZ-800 timing?

I asked for MOTOR and SENSE to be sure if your code is not waiting for these signals when browsing SD card or actions from buttons.

**Comment by bales0** [comment]
> In the loop, we get the input code to act accordingly:
> 
> https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.ino#L952-L974
> 
> You could add serial usb printing to see if a input code is received.
> 
> https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/3d14d01e14415129d7c6f805d5cc58e5bc8e473c/Arduino/mz-sd2cmt/mz-sd2cmt.ino#L137-L168
> 
> As you can see, there is a call to Display.displayCode(...) so I'm a little surprise you won't get here.
> 
> I suppose that you don't have specific issue to access SD (though Storage instance).
> 
> As for MOTOR and SENSE, there are used when you call playWAV(); or playMZF();

I have used different SD card and FAT32 and FAT format to check if the issue is not SD card. But didnt help, still no reaction from keypress. Just ADC value from terminal.

**Comment by bales0** [comment]
> Sorry, I was so busy with my work that I didn't watch my emails. So in the end, you got values when pressing keys (I see some hexa values). Did you change the values BV0-BV4 according to what you read? Because if you didn't change them, it is normal that there is no feedback to LCD since the difference is bigger than the delta value.
> 
> The values should be : static constexpr int BV0 = 0x0000; // TODO: make it configurable at run-time? static constexpr int BV1 = 0x0083; // TODO: make it configurable at run-time? static constexpr int BV2 = 0x0133; // TODO: make it configurable at run-time? static constexpr int BV3 = 0x01DF; // TODO: make it configurable at run-time? static constexpr int BV4 = 0x02D0; // TODO: make it configurable at run-time?

Yes, used exact these values from terminal.
Do you think the problem is the compiler from Arduino? As I understand you have used Visual Studio Code. Maybe this is why I received this error from terminal: "The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter."

**Comment by hlide** [comment]
Try to add serial messages after "if (InputReader.readCode(inputCode))" to check whether it really gets the input codes. I don't understand why it doesn't work.

**Comment by hlide** [comment]
As far as I know, the tape system is totally similar to MZ-700. And you're right it must be checked upon MZ-800 schematics instead.

**Comment by hlide** [comment]
Checked the doc, the timing is the same.

**Comment by bales0** [comment]
> Try to add serial messages after "if (InputReader.readCode(inputCode))" to check whether it really gets the input codes. I don't understand why it doesn't work.

Hi,
Ive added Serial print of InputCode like this (please check if it is right as I do not understand the code):
"
void loop()
{
	Osp3.setLevel(0);

	SerialCode	serialCode = SerialCode::none;
	InputCode	inputCode = InputCode::none;

	if (SerialPrompt.readCode(serialCode))
	{
		// Do something with Serial?
	}

	if (InputReader.readCode(inputCode))
	{
  
  Serial.print(InputReader.readCode(inputCode));
  
		switch (inputCode)
		{
		case InputCode::right:
			rightPressed();
			break;
		case InputCode::left:
			leftPressed();
			break;
"
But no new information on serial monitor. Just ADC values.

**Comment by hlide** [comment]
Try to comment/remove those lines:
https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.ino#L947-L950

I wonder if they block upon it.

Or maybe one of the input modules is blocking.

But you say you can see hexa codes when pressing which means at least the input loop is working.

**Comment by hlide** [comment]
Oh your code is not good.

Do something like that:
```
SerialCode	serialCode = SerialCode::none;
InputCode	inputCode = InputCode::none;

if (SerialPrompt.readCode(serialCode))
{
	// Do something with Serial?
}

if (InputReader.readCode(inputCode))
{
	Serial.println(inputCode);

```

**Comment by hlide** [comment]
What may happen is that `InputReader.readCode(inputCode)` is always returning false. Let me check the condition.

**Comment by hlide** [comment]
Also, you can disable unused input modules:

https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.input.h#L3-L5

by setting them as:
```
#define HAS_INPUT_KEYPAD 1
#define HAS_INPUT_IRREMOTE 0
#define HAS_INPUT_ROTARY_ENCODER 0
```

**Comment by bales0** [comment]
> Oh your code is not good.
> 
> Do something like that:
> 
> ```
> SerialCode	serialCode = SerialCode::none;
> InputCode	inputCode = InputCode::none;
> 
> if (SerialPrompt.readCode(serialCode))
> {
> 	// Do something with Serial?
> }
> 
> if (InputReader.readCode(inputCode))
> {
> 	Serial.println(inputCode);
> ```

This I used, but linker shows this error:

exit status 1
no matching function for call to 'HardwareSerial::println(InputCode&)'

**Comment by bales0** [comment]
> Also, you can disable unused input modules:
> 
> https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.input.h#L3-L5
> 
> by setting them as:
> 
> ```
> #define HAS_INPUT_KEYPAD 1
> #define HAS_INPUT_IRREMOTE 0
> #define HAS_INPUT_ROTARY_ENCODER 0
> ```

This I tried the first day but linker showed:

exit status 1
'DummyInput' is an ambiguous base of 'InputReaderSelector<DummyInput, KeyPadInput, DummyInput>'

**Comment by bales0** [comment]
What surprised me on terminal is that it shows that Rotary encoder is used:
"
Input device: rotary encoder.
MZ-SD2CMT
         0 2024-08-05 18:34 jason/
133
133
83
84
2D0
1DF
1DF
0
0
"

**Comment by hlide** [comment]
https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.input.h#L71

Also replace with: `struct InputReader : InputReaderSelector<KeyPadInput>`

**Comment by bales0** [comment]
> https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.input.h#L71
> 
> Also replace with: `struct InputReader : InputReaderSelector<KeyPadInput>`

Now at least monitor doesnt show rotary encoder as input :)
"
MZ-SD2CMT
         0 2024-08-05 18:34 jason/
"
But still no reaction from keypress

**Comment by hlide** [comment]
It makes no sense: you have `InputReader.readCode(inputCode)` returning true when serial displays the hexa value. So you should then get another serial message which outputs the numerical value of inputCode.

Replace `Serial.println(inputCode);` with `Serial.print("InputCode: "); Serial.println(inputCode);`

So you should have "InputCode: x" where x is a integer value.

**Comment by bales0** [comment]
I have to use:
	if (InputReader.readCode(inputCode))
	{

    Serial.print("InputCode: ");
    Serial.println((InputReader.readCode(inputCode)));

As:
Serial.print("InputCode: "); Serial.println(inputCode);
return error during compilation

But still no new text in monitor, which as I understand the conditions means that its not met and boolean of keypress is 0.

When I put SerialPrint without condition I got no matter if key is pressed:

InputCode: 0

**Comment by hlide** [comment]
You don't have to call `Serial.println((InputReader.readCode(inputCode)));` this way because you are replaying the button detection but it would always return false because the next reading will find the same key pressed and then return false to avoid too fast repetitive input_code. If you press 'SELECT', it will issue one code then nothing until you release and repress or after a period so holding a key is not flooding too much.

**Comment by hlide** [comment]
Try `Serial.println(int(inputCode));` instead.

**Comment by hlide** [comment]
Also, https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L6

Try struct `KeyPadInput : InputReaderSelector<LCD16x2KeyPadV1Input>`

**Comment by hlide** [comment]
That project is getting old. Going to vacation from tomorrow. I'll be absent for at least two days. Then I'll try to see if I can update all the source with a more recent Arduino 2.0 and toolchain. It really makes no sense, if you can display an hexa value when pressing a key then `InputReader.readCode(inputCode)` will return true and update inputCode. The source I read is not lying about it.

**Comment by bales0** [comment]
Hi,
thanks for new ideas. I will try.
Enjoy the vacation!

**Comment by hlide** [comment]
Gosh! Using Arduino 2.0, I stumble upon many issues. I have numerous errors when compiling. Also notice the toolchain is quite old and stuck to c++11. It looks like their last version is leading to many C++ regressions...

**Comment by hlide** [comment]
Ok, after some works to make it buildable and uploadable, I seem to get the same issue as you. Looks as if I cannot trust Arduino in the long term... I guess I need some time to solve that mystery.

At least rotary encoder works. I can explore the contents of the µSD.

**Comment by hlide** [comment]
My bad! I happen to find why keypad is not working. It is true that I wasn't using that screen and keypad that much after having been switching to OLED, rotary encoder and IR remote. And people who built their MZ-SD2CMT before you, weren't using that keypad so you are the only one to discover that bug. Thanks for letting me pinpoint it.

You should remove "bool " before result in https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L95
to get:
```
			result = received_code != InputCode::none;
			if (result)
			{...
```

**Comment by bales0** [comment]
> Gosh! Using Arduino 2.0, I stumble upon many issues. I have numerous errors when compiling. Also notice the toolchain is quite old and stuck to c++11. It looks like their last version is leading to many C++ regressions...

Hi,
thats why I install "old" version of Arduino 1.8.5 as I have experienced compilation errors with other older projects.

**Comment by bales0** [comment]
> Ok, after some works to make it buildable and uploadable, I seem to get the same issue as you. Looks as if I cannot trust Arduino in the long term... I guess I need some time to solve that mystery.
> 
> At least rotary encoder works. I can explore the contents of the µSD.

I thought that not many of us are using simple keypad in this project (and based message from terminal), so I also had plan to order rotary encoder just to try.

**Comment by bales0** [comment]
> My bad! I happen to find why keypad is not working. It is true that I wasn't using that screen and keypad that much after having been switching to OLED, rotary encoder and IR remote. And people who built their MZ-SD2CMT before you, weren't using that keypad so you are the only one to discover that bug. Thanks for letting me pinpoint it.
> 
> You should remove "bool " before result in
> 
> https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/fd4bad282d7dc0027287e2038f02f6aa5ba8421c/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L95
> 
> 
> to get:
> ```
> 			result = received_code != InputCode::none;
> 			if (result)
> 			{...
> ```

WAUUU, now it is working as expected! I dont know how to thank you for your invested time to help me.
Now it shows Playing... There is no progress, but Im sure it is because it is not connected to MZ800 port.
As I think, there should be possible to switch to "normal" mode by RIGHT key. Should it be shown on LCD? It is shown in terminal sometimes when loading.
Oh, I can see that "sometime" ULTRAFAST written on terminal is because of doubletap the key. Enable and disable with one keypress.
Again THANK YOU. Im looking forward to test with the SHARP!
Later I will try to understand the code to the level I would be able to add ULTRAFAST mode switch to be seen on display :-)

**Comment by bales0** [comment]
Could I have one more ask for help?
Im not able to compile MZF2LEP in MinGW and there is no build included in your project.
Maybe you have compiled version for Windows to share with me or add here to repository?

**Comment by hlide** [comment]
It is for creating LEP files. Just using WAV or MZF files should be enough (just dropping them in the SD). I will see it tomorrow.

**Comment by hlide** [comment]
ULTRAFAST mode is also displayed on both LCD and OLED screens.

Your LCD:
https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/5d70a8ce874490515b11ab1d42df08c5a77b79b5/Arduino/mz-sd2cmt/mz-sd2cmt.display.lcd16x2.h#L161-L163

EDIT: for some reason, I cannot see anything displayed on the second line. Well, another thing I must check.

**Comment by hlide** [comment]
https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/5d70a8ce874490515b11ab1d42df08c5a77b79b5/Arduino/mz-sd2cmt/mz-sd2cmt.display.lcd16x2.h#L159-L168

It sounds pretty weird to redraw the second line only when not refreshing all. Maybe it should be `if (refresh_all)`.

EDIT: yep, OLED is doing the opposite thing so it should be `if (refresh_all)`. I checked and it is better.

**Comment by bales0** [comment]
Hi,
yes! Now it shows speed mode. I can see in code STOP, PAUSE, RESUME, is it functional? I have to rest to stop PLAYBACK.
Is there a code implemented to eliminate switch bounce? Repeat delay is OK, but bouncing of the keys makes doubleclick occur at 70%. But this is not such a problem, just asking.
Tomorrow I will try to connect to MZ800.

**Comment by hlide** [comment]
I was not using that LCD KEYPAD since I used OLED + Rotary encoder + IR remote because that keypad is a pain in the arse to use. The issue I got is sometimes the pressed key is not acquired.

EDIT: Since I corrected that line, it seems to work better:
https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/5d70a8ce874490515b11ab1d42df08c5a77b79b5/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L127-L131

By:
```
				else
				{
					repeat_count = 0;
					previous_code = code = InputCode::none;
				}
```

We read the voltage every 10ms, not under. Maybe I should increase that period.

**Comment by hlide** [comment]
PAUSE and RESUME is because when MOTOR respectively goes 0V and 5V from the MZ side. You can press SELECT during PAUSE to CANCEL the loading. STOP is when you reach the end of your loading (message si "Done in...").
They should work but as long as you connected the tape connector.

**Comment by hlide** [comment]
Ok, I was using an old IRremote library and I can see more serial messages about using an obsolete API so I must also fix it. Now I'm using Arduino 2.3.2 and try to add a configuration file of each input or output module.

**Comment by bales0** [comment]
Hi, Ive tried with real MZ800 and it is working! Awesome speed Flappy in seconds. Both normal and ultra-fast mode works.
Some of multipart games also work. I have to play more to check why just some.
Note that I have to mirror CMT connector numbering in oposite the connection diagram.
Now I have to figure out how to inbuild to MZ800 case so it would looked nice and "original".
Thank you, good job!

**Comment by hlide** [comment]
> Could I have one more ask for help? Im not able to compile MZF2LEP in MinGW and there is no build included in your project. Maybe you have compiled version for Windows to share with me or add here to repository?

You need Visual Studio Development Prompt launched in _...\MZ-SD2CMT\Tools\mzf2lep\prj_ then type `build.bat`. The binary will then be in _...\MZ-SD2CMT\Tools\mzf2lep\bin_.

But I added a Release for it (compiled under Visual Studio 2022): https://github.com/SHARPENTIERS/MZ-SD2CMT/releases

**Comment by bales0** [comment]
> > Could I have one more ask for help? Im not able to compile MZF2LEP in MinGW and there is no build included in your project. Maybe you have compiled version for Windows to share with me or add here to repository?
> 
> You need Visual Studio Development Prompt launched in _...\MZ-SD2CMT\Tools\mzf2lep\prj_ then type `build.bat`. The binary will then be in _...\MZ-SD2CMT\Tools\mzf2lep\bin_.
> 
> But I added a Release for it (compiled under Visual Studio 2022): https://github.com/SHARPENTIERS/MZ-SD2CMT/releases

Hi,
thank you for help.
Anyway I will just try to compile by myself to learn something new for me.

EDIT: I was missing MSVC compiler toolkit, after install able to compile :-) THX!

**Comment by bales0** [comment]
> I was not using that LCD KEYPAD since I used OLED + Rotary encoder + IR remote because that keypad is a pain in the arse to use. The issue I got is sometimes the pressed key is not acquired.
> 
> EDIT: Since I corrected that line, it seems to work better:
> 
> https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/5d70a8ce874490515b11ab1d42df08c5a77b79b5/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L127-L131
> 
> By:
> 
> ```
> 				else
> 				{
> 					repeat_count = 0;
> 					previous_code = code = InputCode::none;
> 				}
> ```
> 
> We read the voltage every 10ms, not under. Maybe I should increase that period.

Hi,
I think that the problem is not that key is not aquired, but that it is aquired two times as LCD is redrawn with each keypress. But sometimes no change in "normal" "ultra-fast mode" parameter text.
It is clearly visible by browsing files on SD, sometimes it overjump one file with one press.
This is not a big issue for me, Im happy that we got it working on this level!

**Comment by hlide** [comment]
My last commit (needs to update Arduino IDE and libraries) contains some changes :
Each button of the keypad except for UP and DOWN are now not repetitive when holding the key so you shouldn't have that issue  with the last commit and it works perfectly on my prototype. By the way, the LCD is so damn slow to refresh that I opted for an OLED which is more confortable for your information (you can aggregate display modules, they will work simultaneously).

**Comment by bales0** [comment]
Hi,
now it is possible to compile in Arduino 2.3.2, but "#include "mz-sd2cmt.std.h"" has to be deleted.
Where is the configuration file created in Windows, so it can be edited? There is no ADC values in terminal, just 0 of SELECT key (as it is 0 in always). So unknown values to be changed to for configuration.
However I have already ordered OLED and rotary encoder to get benefits from these peripherials, even 16x2 LCD looks better to 8-bit computer. :-)

**Comment by hlide** [comment]
Ah sorry, this file is always in my local repository. I must really remove its #include.

As for the configuration file, you must run the firmware first so it can create those files with default values. They are created in the hidden .config directory in the root of your SD. The file is LCD_KEYPAD_SHIELD.input in your case.

By the way, the offsets output on serial debug are wrong. I must also commit a correction for them.

Since you seem to recompile yourself the firmware, you can modify the source here: https://github.com/SHARPENTIERS/MZ-SD2CMT/blob/80ad3f5e68fa381461a6da2187f804954ba78b5c/Arduino/mz-sd2cmt/mz-sd2cmt.input.keypad.h#L12-L21

EDIT: Corrections commited.

**Comment by hlide** [comment]
Calibration for KEYPAD is now added. If the configuration is missing or invalid, serial monitor will prompt a calibration is needed and will ask for pressing each buttons distinctly to hint their voltage levels.

**Comment by bales0** [comment]
Hi,
nice! It works. If I need to recalibrate, I can just delete config files. One note and proposal, what about to use LCD as guidance for calibration? Its not clear what key is 1, 2, 3, why not to call them by function? LEFT, RIGHT, SELECT...? In this case user can set any ADC - keyposition configuration. As I can see from calibration procedure, code recognises which key is pressed, as I didnt went through 1,2,3,4,5 acordingly and it asigns right ADC value to right key. So maybe no calibration is needed (but maybe just coincidence as I try just once and it works) :-)
Again, I would like to thank you for such friendly and quick support!

**Comment by bales0** [comment]
Oh, now I can see. It just scans ADC values for all the keys and then asigns to functions as LCDKEYPAD schematics is always the same (keypad resistor ladder) - clever. 👍 

EDIT: I saw that you explained this aproach of schematics similarities of LCDKEYPAD already. Took me few minutes to realize :-)

**Comment by hlide** [comment]
Yes, I gambled that the voltage scale would remain the same, so all you had to do was press in any order and then sort the voltages in ascending order so that magically the right buttons were associated with the right voltage.

I've already added the possibility of displaying the calibration on all the displays but I had to comment their code out except for the serial because I had garbage on the LCD. The other problem is that I don't have many characters per line on the LCD, so I've decided to display only on the serial display for the time being.

**Comment by bales0** [comment]
> Also, you can join me at https://discord.com/channels/1197483745389854760/1208344566521004073.

Hi,
Im trying to join you at discord.
Just like to discuss if it is possible to add also record function. No matter if to WAV or LEP or any other format suitable to sample MZ800 dataflow. This would totally substitute CMT as if MZ-SD2CMT is used no external casette recorder could be connected.
Maybe some simple dataloger when SAFE possible?

**Comment by hlide** [comment]
Ah, you must be "ales" who tried to invite me. Sorry, I saw it but with no message and no idea who ales was, I didn't answer.

There was a time I also wanted to record as WAV/LEP/MZF file but I wasn't sure how to achieve it correctly.
